name: Publish Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # This gives write permissions for committing changes to the repository
  packages: write  # This is needed if you are publishing packages

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Install dependencies
      run: pnpm install

    - name: Build packages
      run: pnpm run build

    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          npx semantic-release --dry-run
        else
          npx semantic-release
        fi

    - name: Push changes back to repository
      if: github.event_name == 'push' && success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout main
        git add -A
        git commit -m "chore(release): commit changelog and package.json updates [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
